name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - main   # ⚠️ 你的預設分支，確認是不是 main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --trace

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

<a href="{{ '/' | relative_url }}" class="{% if page.url == '/' %}active{% endif %}">首頁</a>
<a href="{{ '/about/' | relative_url }}" class="{% if page.url == '/about/' %}active{% endif %}">關於我</a>
<a href="{{ '/articles/' | relative_url }}" class="{% if page.url == '/articles/' %}active{% endif %}">文章</a>
<a href="{{ '/resources/' | relative_url }}" class="{% if page.url == '/resources/' %}active{% endif %}">資源</a>
<a href="{{ '/contact/' | relative_url }}" class="{% if page.url == '/contact/' %}active{% endif %}">聯絡</a>
